spring:
  application:
    name: camunda-app

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin


camunda-base-url: http://localhost:8080/engine-rest

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE